### ISSUE TITLE
Width of Japanese half-width Katakana is incorrect.

### ISSUE THREAD

**Issue by SyuueenN** [SolidZORO/zpix-pixel-font#10]
I found a problem of Zpix that width of Japanese half-width Katakana(such as ｲﾛﾊﾆﾎﾍﾄ) is incorrect, these characters displays in full-width. Please fix this problem.

我在使用Zpix时发现半角片假名（如：ｲﾛﾊﾆﾎﾍﾄ）的宽度不正确，它们以全角宽度显示，请作者修复一下这个问题。

**Comment by SolidZORO** [comment]
fixed see https://github.com/SolidZORO/zpix-pixel-font/tree/master/dev
