### ISSUE TITLE
这款字体只有12px点阵吗？

### ISSUE THREAD

**Issue by widon1104** [SolidZORO/zpix-pixel-font#11]
我正在使用Zfull gb字体，Zfull gb字体的12px点阵就是使用zpix吗？
现在9px感觉用的很多，而Zfull gb 9px的点阵感觉不是很好看，不知道有没有计划开发9px点阵

**Comment by SolidZORO** [comment]
没有开发 9px 的计划。zFull 是刚开发字体时合成各种字号的练手作品，已不再维护。

----

Jason Fung

[ Developer, Designer ]

在 2018年11月28日，13:49，widon1104 <notifications@github.com<mailto:notifications@github.com>> 写道：


我正在使用Zfull gb字体，Zfull gb字体的12px点阵就是使用zpix吗？
现在9px感觉用的很多，而Zfull gb 9px的点阵感觉不是很好看，不知道有没有计划开发9px点阵
