### ISSUE TITLE
bdf格式全角符号，和。的位置偏移到前一个字符

### ISSUE THREAD

**Issue by Kzinux** [SolidZORO/zpix-pixel-font#13]
如图所示。
![fh](https://user-images.githubusercontent.com/7030257/57192139-b887e200-6f5f-11e9-86f7-8a675bef8b8e.png)

**Comment by SolidZORO** [comment]
我先 TODO 一下。

好不容易看到一个只要修 bdf 的 issues，比起修 bdf + ttf 的问题容易一万倍。但结果……我在新版本 macOS 上跑不起来 fontforce, 原因是 fontforce 依赖的 XQuartz 在高版本的 macOS 下跑不起来，先作罢。待我跑起来了会修复。

**Comment by Kzinux** [comment]
好的，麻烦您了。

**Comment by SolidZORO** [comment]
![image](https://user-images.githubusercontent.com/661587/65710834-54a8b600-e0c6-11e9-882d-2dee658435b5.png)


Hello，问题已修复，可在 https://github.com/SolidZORO/zpix-pixel-font/tree/master/dev 获取最新版本。
