### ISSUE TITLE
Looks very weird in Emacs

### ISSUE THREAD

**Issue by geokon-gh** [SolidZORO/zpix-pixel-font#15]
I'm not sure what the exact problem is, but the font looks very strange in Emacs. It seems the spaces and tabs are very narrow - so it doesn't behave like a normal monospaced font and everything ends up misaligned.

Maybe I misunderstood something and it's not a monospaced font

**Comment by SolidZORO** [comment]
@geokon-gh can you take a screenshot?

**Comment by geokon-gh** [comment]
![zpix-bug](https://user-images.githubusercontent.com/21017379/61941183-8ff50e80-afc9-11e9-9c23-bc241ec92391.png)

**Comment by geokon-gh** [comment]
A little hard to see, but you can see how the character columns don't line up in the code - not to mention the indentation is all off

**Comment by geokon-gh** [comment]
I also just double checked and it looks the same when I don't load any `init.el`

**Comment by SolidZORO** [comment]
@geokon-gh 刚发现原来你是国人，用中文吧。我看不出到底你想表达什么问题，可否在图中画个圈？我是 vi 用户，从未用过 ecmas，刚想在 OSX 上尝试，然后表示退不出来了…… 作罢。你先描述一下你想要实现的效果吧。

**Comment by geokon-gh** [comment]
Haha, 不是中国人. Sorry. Just live in China right now. 我的中文有点不好

**Comment by geokon-gh** [comment]
![zpix-bug-ZOOM](https://user-images.githubusercontent.com/21017379/61943671-8b7f2480-afce-11e9-820b-eac6b2ad7223.png)

**Comment by geokon-gh** [comment]
1 - the 2 "m"s are not aligned
2 - the indentation is not correct. That block should look like this:

``` clojure
	(recur (submatrix input-matrix
			  1
                          (dec (row-count input-matrix))
			  1
			  (dec (column-count input-matrix)))))))
```
When I switch to a different font (without changing the code) it looks correct

**Comment by SolidZORO** [comment]
hhhh, my bad. I understand. The regular version of Zpix is ​​not suitable for use in the code editor. 

In fact, if you need to display the code, you can try https://raw.githubusercontent.com/SolidZORO/zpix-pixel-font/17ed553200850f99de2bdb4aab4ad4e0b89b5984/dist/Zpix_CODE_2.0.ttf

**Comment by geokon-gh** [comment]
Oh okay, then I'll close this issue, no problem. I appreciate your work and getting back to me


PS: The `ttf` you linked also doesn't display correctly in Emacs and doesn't show up as a bitmap unfortunately

**Comment by geokon-gh** [comment]
btw, what made you think I was Chinese? :)

**Comment by SolidZORO** [comment]
Hahaha, I just saw your avatar, inside is the Chinese building, and your location is written in Sichuan.

Zpix_CODE is my work ten years ago. I was still using Windows XP, and I didn't turn on anti-aliasing. Everything was fine. Because this font has no vector part in order to control the size, there is only a BDF (a pixel font type). So after turning on anti-aliasing, the BDF is ​​not displayed, and this font has no vector part. So this problem has arisen.

**Comment by geokon-gh** [comment]
ohhhh right! Forgot about that! hahaha

Thanks! And yeah, it's not a big deal. I appreciate you trying to help :)
