### ISSUE TITLE
请问有没有可能增加纯等宽版本？ 

### ISSUE THREAD

**Issue by ATiGr** [SolidZORO/zpix-pixel-font#17]
Zpix字体真的是很特别，点阵中文的美感绝无仅有，和等宽英文的融合度之高也让人惊喜，所以非常希望可以在Terminal还有IDE里面作为默认编辑字体使用。

但是很遗憾的发现，目前大部分符号都不是等宽的（最新的stable版和beta3.0.2版都尝试了），所以想请教一下，是否有可能发布一个纯等宽版本的字体？如果可以那真的非常感谢！

**Comment by SolidZORO** [comment]
非常抱歉，由于 macOS 目前不支持 32bit 的所有字体 App，我暂时无法做任何修改，当然现在也忙，我是有计划重构一版 Zpix 的但还是要看时间。你的这个问题我先写到 TODO，到时重构的时候一并做好。BTW，如果想要用于 CODE，我记得 10 年前我做过一个面向 CODE 的版本，你试试看 https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/zpix/Zpix%20C.O.D.E_ver2.0.ttf

**Comment by ATiGr** [comment]
感谢回复！CODE版本我刚才试了一下，遗憾的是中文都不显示了（我在用macOS Catalina），而且字体风格和Zpix不太一样，还是喜欢Zpix哈哈。

macOS对软件的兼容性的坑感觉只会更大了，不知道虚拟机之类的是否可以解决问题？当然我不太懂字体制作，可能虚拟机不能提供足够的性能。

P.S. 如果是todo的话，是不是能再舔着脸request粗体/斜体？当然只是针对英文和符号，在IDE里有很大帮助。中文则是没必要的，工作量浩瀚而且似乎也没有实际用途。感觉粗体斜体可以参考Input Mono, 真的超多自定义的空间。当然我相信您一定比我更了解，班门弄斧了哈。

最重要的还是表达对您的感谢！带来了这么特别且优美的中文字体。衷心希望早日见到Zpix的重构升级版。顺祝万事顺遂～

**Comment by SolidZORO** [comment]
这个其实还蛮有难度的，我其实这几年都不怎么敢改 Zpix。

以前做 bitmap（bdf）还好，做完直接 cmd+s 就可以发布了。但是后来为了兼容在游戏中显示，我套了个矢量 TTF 的壳在 bitmap 上。这个 TTF 怎么得到的呢？就是给 bitmap 取模，这一步很多工作量，batch 处理后需要个别字逐个微调，所以每改一个字，都需要做一遍这个步骤，如果不做 bitmap 和 TTF 就不同步了，这个是不能忍的。

好～谢谢你的所有提案，我后面会处理的，当然时间可能不会是最近。😂

**Comment by ATiGr** [comment]
原来如此，正是不懂里面的难度才会舔着脸提需求，抱歉哈。那我其实最核心的就是希望有个等宽版，没有粗体没有斜体我靠自己脑补（以及IDE的颜色），哈哈。

哦，另外我还有一个疑惑，我在项目Release页下载的历史版本，比如3.0.1，1.2.1，都只提供了 zip/tar.gz 的下载，下载解压之后的内容似乎都是一样的？比如 dist 文件夹下的 zpix.ttf 都是相同的md5 (783bb457ed9b3294fe72f4b4bc9358a9), 在 FontForge 里面看到的版本号都是 1.000。 这是为什么呢？

所以是否有3.0.1/1.2.1的ttf版本可以下载使用呢？

**Comment by SolidZORO** [comment]
发版估计是多点了发布，而没有清理，我待会去清理一下。然后 FF 里面的版本号我没去设定他，只是默认的，其实 FF 里面有好几个版本号，或者留 MEMO 等信息，我也不知道那个正确，所以就保持默认了。

**Comment by ATiGr** [comment]
明白了，再次感谢回复哈！那这个issue我就close掉啦。祝您每天都有好心情～

**Comment by ATiGr** [comment]
猛然发现大佬开始更新了诶！！悄悄再问下是否可能安排 真等宽 选项？

**Comment by SolidZORO** [comment]
因为我终于找到了比较好用的 bdf 转 ttf，而且可以写脚本去自动化…… 从之前的修一个 pixel 需要搞半个多小时到现在的一分钟，所以还是比较有更新动力的。

你所说的「真等宽」可以配合 https://zpix.now.sh/ 给我来一些范例吗？

**Comment by ATiGr** [comment]
做了一个简单的范例对比。对比的字体是我比较喜欢的一个等宽字体家族：Input Mono，以及不等宽的变体 Input Sans

仅供参考哈！就如去年我说的，特别希望可以在编辑器环境里用上zpix，所以很期待等宽～

<img width="704" alt="mono" src="https://user-images.githubusercontent.com/3756892/98546195-87653c00-22d1-11eb-8d32-801268bac989.png">

**Comment by SolidZORO** [comment]
原来你要的是用于编辑器的等宽啊，我 2015 年的时候就做过尝试，你试试。

[Zpix_C.O.D.E.zip](https://github.com/SolidZORO/zpix-pixel-font/files/5514719/Zpix_C.O.D.E.zip)

**Comment by ATiGr** [comment]
> 原来你要的是用于编辑器的等宽啊，我 2015 年的时候就做过尝试，你试试。
> 
> [Zpix_C.O.D.E.zip](https://github.com/SolidZORO/zpix-pixel-font/files/5514719/Zpix_C.O.D.E.zip)

我试过的，字符不太一样，而且主要没有汉字啊

**Comment by SolidZORO** [comment]
应该是的了，当时没有放矢量字模进去。因为 10 年前还在 windows 下面并且关掉了 clear type。

最近特别忙，可能没有时间再做一个专门 for code 的版本了。如果你觉得自己行，可以用 src 的文件试试编译看看。

**Comment by LuRenJiasWorld** [comment]
@ATiGr Hello，我使用项目主干的文件对字体进行了修改（西文字体7px，全角字体14px，刚好可以实现等宽），并进行了居中处理，如果有需要可以来这里下载：https://github.com/LuRenJiasWorld/zpix-pixel-font

效果截图：
![image](https://user-images.githubusercontent.com/29622423/153007449-69657166-041c-42a3-80e9-6070bcbbde73.png)

@SolidZORO 也许可以将这个Fork后的仓库链接附在主项目的README里，方便有需要的用户自行获取？或者我抽空再写一个 Python 脚本，将 Regular 字体按 Unicode 分区自动化也行~

**Comment by ATiGr** [comment]
> @ATiGr Hello，我使用项目主干的文件对字体进行了修改（西文字体7px，全角字体14px，刚好可以实现等宽），并进行了居中处理，如果有需要可以来这里下载：https://github.com/LuRenJiasWorld/zpix-pixel-font
> 
> 效果截图： ![image](https://user-images.githubusercontent.com/29622423/153007449-69657166-041c-42a3-80e9-6070bcbbde73.png)
> 
> @SolidZORO 也许可以将这个Fork后的仓库链接附在主项目的README里，方便有需要的用户自行获取？或者我抽空再写一个 Python 脚本，将 Regular 字体按 Unicode 分区自动化也行~

You’re my hero!! 真的是意外惊喜啊！万分感谢！

**Comment by LuRenJiasWorld** [comment]
> > @ATiGr Hello，我使用项目主干的文件对字体进行了修改（西文字体7px，全角字体14px，刚好可以实现等宽），并进行了居中处理，如果有需要可以来这里下载：https://github.com/LuRenJiasWorld/zpix-pixel-font
> > 效果截图： ![image](https://user-images.githubusercontent.com/29622423/153007449-69657166-041c-42a3-80e9-6070bcbbde73.png)
> > @SolidZORO 也许可以将这个Fork后的仓库链接附在主项目的README里，方便有需要的用户自行获取？或者我抽空再写一个 Python 脚本，将 Regular 字体按 Unicode 分区自动化也行~
> 
> You’re my hero!! 真的是意外惊喜啊！万分感谢！

举手之劳，恰好我也需要等宽版本用于终端字体，不用谢的，祝新年快乐！
