### ISSUE TITLE
统一字母

### ISSUE THREAD

**Issue by tanukihee** [SolidZORO/zpix-pixel-font#18]
在3.02dev版本中，重音字母终于不是再是全宽的了，但部分重音字母与不带重音字母并不统一，如 ǧ、ĝ 与 ǵ 中的 g 均是双层 g，而字母 g 是单层。

另外，如果将来出了等宽版本，希望西文部分为 6×12 或 8×12，方便中文与西文对齐（2:1 或 3:2）。

**Comment by SolidZORO** [comment]
收到。下次（不确定何时）累积了一些 issues 我再动作把。
