### ISSUE TITLE
U+99C4 駄 has the wrong bitmap

### ISSUE THREAD

**Issue by simon-nicalis** [SolidZORO/zpix-pixel-font#19]
See screenshot 
![grafik](https://user-images.githubusercontent.com/55413765/78015845-42942280-734a-11ea-8703-fb5cb26fdd32.png)
as well as pull request https://github.com/SolidZORO/zpix-pixel-font/pull/20

**Comment by SolidZORO** [comment]
thanks, updating `bdf` is simple now, but updating `ttf` synchronously is difficult. In any case, do what we can first.
