### ISSUE TITLE
Is is available for project under GPL 3?

### ISSUE THREAD

**Issue by wusyong** [SolidZORO/zpix-pixel-font#23]
Hello, currently I have an open source project licensed under GPL 3. Is it free to use it? And how do we mention your custom license?

**Comment by SolidZORO** [comment]
Zpix licensing only cares if your project is commercial or non-commercial. If your project is not commercial (or educational), it is free to use. Then put the project's README.md in the font directory.

----

Zpix 授权只关心你的项目是否商用。假如你的项目非商用（或教育用途），是可以免费使用的。然后把项目的 README.md 放到字体目录下即可。

**Comment by wusyong** [comment]
Thanks! I will remember to do that.
