### ISSUE TITLE
Some latin letters such as "ü" are taking full-width space instead of half-width

### ISSUE THREAD

**Issue by bitinn** [SolidZORO/zpix-pixel-font#3]
I didn't realize this until I tried, not sure how you want to handle it, I think they should be half-width like other English letters.

![screen shot 2016-05-05 at 6 00 47 pm](https://cloud.githubusercontent.com/assets/1484279/15040991/56f45466-12eb-11e6-87bd-80189ec9b717.png)

**Comment by fluviusmagnus** [comment]
The same problem also occurs in some frequently used (really basic) extended latin letters e. g. üöäáóê... Maybe a thorough check is needed.
It is really worth a fix.

**Comment by SolidZORO** [comment]
fixed see https://github.com/SolidZORO/zpix-pixel-font/tree/master/dev
