### ISSUE TITLE
缺少韩文点阵

### ISSUE THREAD

**Issue by Mapaler** [SolidZORO/zpix-pixel-font#30]
您好，我在做游戏图鉴，尝试添加韩语版本发现缺少韩文的点阵。请问是否有添加韩文点阵计划。
![Screenshot_2020-12-14-18-50-47](https://user-images.githubusercontent.com/6565860/102073661-9b570d00-3e3e-11eb-9e07-7e2cf5ace696.png)
<hr>

关于lisence，我这个是免费开源项目，可以用吧？
https://github.com/Mapaler/PADDashFormation
用在这里
![Screenshot_2020-12-14-19-08-10](https://user-images.githubusercontent.com/6565860/102074451-c7bf5900-3e3f-11eb-9769-c7d6448254c1.png)

**Comment by SolidZORO** [comment]
Hey，缺少韩文是正常的，因为没有包含。后续也没有加入韩文的计划。

因为韩文基数很大，大概 6K 左右，做起来要耗费很多时间。你可以找一些韩文点阵 fallback 一下就好。

**Comment by Mapaler** [comment]
原来如此，感谢。我还以为韩文和日文一样，就那几个字符呢。
