### ISSUE TITLE
字体错误；路径的“径”

### ISSUE THREAD

**Issue by Acoustic-exe** [SolidZORO/zpix-pixel-font#36]

**Comment by SolidZORO** [comment]
![image](https://user-images.githubusercontent.com/661587/115177546-0886f180-a102-11eb-85ab-1bdb7b31ee49.png)


感觉中宫有点太饱满了，但是暂时找不到更好的写法。

**Comment by tanukihee** [comment]
日标右边就是圣嘛，我以为是设计特色呢
但确实跟经不同

**Comment by SolidZORO** [comment]
@tanukihee 不是设计特色。我怀疑是我最开始用 Windows XP 的时候，装了一些极限主题上的字体作为系统字体，然后 FF 上的字体显示的是日文或者韩文之类的，导致我照着画，就变成了这个样子。

**Comment by tanukihee** [comment]
未来会改成完全国标吗，那岂不是缺了许多味道😂😂

**Comment by SolidZORO** [comment]
不会大改了，主要是没时间，以维护为主。
