### ISSUE TITLE
Comparing rendering at 12px and 24px

### ISSUE THREAD

**Issue by bitinn** [SolidZORO/zpix-pixel-font#4]
This is the result from previously release:

![screen shot 2016-05-05 at 6 25 29 pm](https://cloud.githubusercontent.com/assets/1484279/15041587/a71f1670-12ef-11e6-9cf8-3bd56a039dd7.png)
![screen shot 2016-05-05 at 6 26 08 pm](https://cloud.githubusercontent.com/assets/1484279/15041599/bd892342-12ef-11e6-830e-da502042e892.png)

This is the current release:

![screen shot 2016-05-05 at 6 24 24 pm](https://cloud.githubusercontent.com/assets/1484279/15041602/c41502a8-12ef-11e6-9145-f82ffdb574f0.png)
![screen shot 2016-05-05 at 6 26 29 pm](https://cloud.githubusercontent.com/assets/1484279/15041604/c92ad8f8-12ef-11e6-9852-89d5677ea46d.png)

To me, the old one looks better at 12px, the new one looks better at 24px.

Is this by design? Is it possible to have nice rendering at both 12px and 24px?

**Comment by SolidZORO** [comment]
em... get me some time fixed it.

**Comment by SolidZORO** [comment]
your can try again.

![e 2x](https://user-images.githubusercontent.com/661587/36202804-3d3856b4-11c0-11e8-9e98-1bb800938323.gif)

**Comment by bitinn** [comment]
Thx! I might use it in a new project (the last one didn’t get released)

(From my phone)
