### ISSUE TITLE
"天"

### ISSUE THREAD

**Issue by Acoustic-exe** [SolidZORO/zpix-pixel-font#41]
![image](https://user-images.githubusercontent.com/57854561/123747389-76f7e500-d8e5-11eb-80fd-eb63ebdfd310.png)
上长下短，有点像日文的写法

**Comment by SolidZORO** [comment]
谢谢提醒，已修正。 原因可以参考这个 https://github.com/SolidZORO/zpix-pixel-font/issues/36#issuecomment-822267849

**Comment by Acoustic-exe** [comment]
了解
