### ISSUE TITLE
版权问题请教，我希望让这个字体进入 aosc 软件仓库

### ISSUE THREAD

**Issue by ocian** [SolidZORO/zpix-pixel-font#46]
您好，可以让这个字体加进开源 linux 发行版 [aosc OS](https://aosc.io/zh-cn/) 的软件仓库吗？
按照版权协议来看，字体仅仅对商业盈利项目使用收费，而开源 linux 社区是非盈利性质的组织，理论上来说是符合这个字体的许可协议的。
如果字体能够加入软件仓库，aosc 用户就有了一个简单统一的字体获取途径，这样也有利于这个字体被更多的人所了解。
我希望能够获得字体作者的许可，这样可以打消社区维护人员在法律和道德方面的顾虑。
期待您的支持。

> Zpix 最像素 为 SolidZORO 具有完全自主智慧财产权的产品，受《中华人民共和国著作权法》和其它智慧财产权法律法规及国际公约、条约的保护。若非获得 SolidZORO 的明确许可，不可在所授权限以外范围使用本产品。 同时禁止对本字形档软体进行修改、反编译、转换、拆分等反向操作，及非法传播、出售、出租或以其它方式从中牟利。SolidZORO 对上述行为者保留起诉权利。

**Comment by SolidZORO** [comment]
没问题！只是用户使用的时候明确提示一下免费使用的范围即可，就像 README 写的那样。

**Comment by ocian** [comment]
> 没问题！只是用户使用的时候明确提示一下免费使用的范围即可，就像 README 写的那样。

大概可以在软件包里面包含 README 文件，明确提示的话不知道可不可以做

但反正使用方式已经清晰了，感谢您的回复，我去问问 aosc 的开发者

**Comment by eatradish** [comment]
閣下好：

我是 AOSC OS 的開發者，雖然看到了上面閣下的說法，但還是希望閣下能明確在協議上明確「允許個人使用上的可分發」並把 README 中申明的條款放進一個協議文件裡（否則我們無法追蹤協議的更新情況），若閣下允許，我可以提 Pull Request 把這件事做了。

**Comment by SolidZORO** [comment]
@eatradish 好啊，我刚意识到这个 repo 没有 LICENSE 文件，PR welcome。

**Comment by ocian** [comment]
由于字体不开源，无法进入 aosc 软件仓库，计划落空，麻烦 aosc 的维护人员了
