### ISSUE TITLE
是否允许字体转换、拆分？

### ISSUE THREAD

**Issue by SouthFox-D** [SolidZORO/zpix-pixel-font#49]
我希望在我的个人博客引用裁剪后的 `woff2` 格式字体，但我注意到了 `README` 中：

> 同时禁止对本字形档软体进行修改、反编译、转换、拆分等反向操作

但是在 #44 中又提到有需求自行转换……

希望请明确个人非商业使用是否允许对字体进行转换和裁剪操作。

**Comment by SolidZORO** [comment]
Hi，谢谢提醒，我更新了说明。https://github.com/SolidZORO/zpix-pixel-font/commit/3c27dd29e22cebd2444dc621429ec77e81d5f02f

不过对于转换用在自己博客的问题嘛。🤫🤫🤫

**Comment by SolidZORO** [comment]
对了，css 提个建议，最好用上  -webkit-font-smoothing: none; 还有 font-size 最好是 12px 的倍数。

**Comment by SouthFox-D** [comment]
😯 好的，感谢解答。

也谢谢建议，我会去试试的。
