### ISSUE TITLE
Chinese Display Fonts

### ISSUE THREAD

**Issue by NovexxA** [SolidZORO/zpix-pixel-font#5]
@SolidZORO:

Dear Jason,
we will download Fonts, but we didn't see how we can receive a license and an invoice therefore?

Please inform us what we have to do to get it.

Thanks in advance and best regards
Ingrid

**Comment by SolidZORO** [comment]
download url: https://raw.githubusercontent.com/SolidZORO/zpix-pixel-font/master/dist/Zpix.ttf

> Buy
> 
> for Commercial Product (Multiple Project) USD $900
> for Commercial Product (Single Project) USD $500
> for Education Project FREE
> for Personal Project FREE
> 
> My Paypal: solidzoro@live.com
> 
> Because spurt in recent purchase, and the font is my work a few years ago, and I will no longer continue to work in the font of So for people who buy the font, I don't have the ability to offer any form of invoice, can't give you any form of written agreement, please understanding.

oh sorry, I don't have the ability to offer any form of invoice.
