### ISSUE TITLE
请问能否加入 brew cask-fonts 呢？

### ISSUE THREAD

**Issue by kusazh** [SolidZORO/zpix-pixel-font#53]
这样可以用 brew 来更新字体，参见：
https://github.com/Homebrew/homebrew-cask-fonts/blob/master/CONTRIBUTING.md

**Comment by SolidZORO** [comment]
Hi，目前不考虑接入源，如有新版会在这边 https://github.com/SolidZORO/zpix-pixel-font/releases 发布的。
