### ISSUE TITLE
请问，一个人开发的独立游戏在Steam上售卖，是否需要购买字体授权？

### ISSUE THREAD

**Issue by 221Games** [SolidZORO/zpix-pixel-font#54]
请问，一个人开发的独立游戏在Steam上售卖，是属于Personal Product，还是属于Commercial/Business Product (Single Product)？这种情况是否需要购买字体授权呢？谢谢。

**Comment by SolidZORO** [comment]
上架售卖这个属于商业行为了，是需要购买授权的。
