### ISSUE TITLE
有没有可能支持 Unicode 的表情符号？

### ISSUE THREAD

**Issue by XHXIAIEIN** [SolidZORO/zpix-pixel-font#58]
就是小声许个愿...
如果可能有 zpix 版的 emoji 表情符号那就真的泰酷辣！！

Emoji Unicode:
https://apps.timwhitlock.info/emoji/tables/unicode#block-6c-other-additional-symbols

**Comment by SolidZORO** [comment]
目前 Zpix 主要是维护，emoji 没有在计划中，如果要做，还得跟进 Apple 的脚步，时不时会有新 emoji，工作量还蛮大的。
