### ISSUE TITLE
Please consider releasing under GPL or another open source license

### ISSUE THREAD

**Issue by sphaugh** [SolidZORO/zpix-pixel-font#6]
The current "license" is not a license per se. Can you select an actual license for the project?

**Comment by SolidZORO** [comment]
oh, sorry, not without choice, but github LICENSE which I do not need the option, so I wrote a LICENSE (only Chinese),  [https://github.com/SolidZORO/zpix-pixel-font#版權聲明](https://github.com/SolidZORO/zpix-pixel-font#版權聲明) Zpix font although upload the source code, but only as a reference, I think most want to use
  Zpix is a game developer and designer, they do not have the energy to read or modify the source code, of course, I wrote the LICENSE also said, do not modify and decompile.
