### ISSUE TITLE
Lacking of Full-Width Chinese punctuations

### ISSUE THREAD

**Issue by NeoChen1024** [SolidZORO/zpix-pixel-font#7]
This font is lacking full-width chinese punctuations.

**Comment by SolidZORO** [comment]
for example?

**Comment by NeoChen1024** [comment]
"，" and "。"

**Comment by SolidZORO** [comment]
![default](https://user-images.githubusercontent.com/661587/36203723-871cfce6-11c3-11e8-99a0-ddbd5d1bb575.gif)
