### ISSUE TITLE
Some Kanjis in Japanese example texts are weird

### ISSUE THREAD

**Issue by hajimehoshi** [SolidZORO/zpix-pixel-font#8]
They are traditional Kanjis, so they are not wrong, but weird. For example:

樂 should be 楽
惡 should be 悪

BTW, 團 is a wrong kanji there. I think 園 is correct.

**Comment by SolidZORO** [comment]
sorry, I don't understand what you are saying.

if found error, pls push Kanjis unicode. i will check.

**Comment by hajimehoshi** [comment]
I'm taking about the image https://github.com/SolidZORO/zpix-pixel-font/blob/master/assets/img/Zpix_1.0_review@2x.gif

Some kanjis in the Japanese text are weird. I don't know how to fix the image...

**Comment by SolidZORO** [comment]
OK, i get you point. 

this review photo maked at few years ago. so, today i make one again, fixed it.

the error just fro review photo, font file is right : >


hree is new review photo.

![zpix_1 0_review 2x](https://user-images.githubusercontent.com/661587/36202464-dff7a140-11be-11e8-8f6e-60b3ea6b76df.gif)
